In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../../data/processed/feature_engineered_telco.csv")

In [3]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,Avg_Monthly_Spend,Tenure_Group,Charge_Segment,Contract_Risk,Revenue_Per_Tenure
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,Yes,Electronic check,29.85,29.85,No,14.925000,New,Low,3,14.925000
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,No,Mailed check,56.95,1889.50,No,53.985714,Loyal,Medium,2,53.985714
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,Yes,Mailed check,53.85,108.15,Yes,36.050000,New,Medium,3,36.050000
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,No,Bank transfer (automatic),42.30,1840.75,No,40.016304,Loyal,Medium,2,40.016304
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,Yes,Electronic check,70.70,151.65,Yes,50.550000,New,High,3,50.550000

In [4]:
df[['tenure', 'MonthlyCharges', 'TotalCharges']].head()

   tenure  MonthlyCharges  TotalCharges
0       1           29.85         29.85
1      34           56.95       1889.50
2       2           53.85        108.15
3      45           42.30       1840.75
4       2           70.70        151.65

In [5]:
df['Estimated_LTV'] = df['MonthlyCharges'] * df['tenure']

In [6]:
df[['MonthlyCharges', 'tenure', 'Estimated_LTV']].head()

   MonthlyCharges  tenure  Estimated_LTV
0           29.85       1          29.85
1           56.95      34        1936.30
2           53.85       2         107.70
3           42.30      45        1903.50
4           70.70       2         141.40

In [7]:
df['Estimated_LTV'].describe()

count    7043.000000
mean     2279.581350
std      2264.729447
min         0.000000
25%       394.000000
50%      1393.600000
75%      3786.100000
max      8550.000000
Name: Estimated_LTV, dtype: float64

In [8]:
df[['Estimated_LTV']].sort_values(
    by='Estimated_LTV',
    ascending=False
).head()

      Estimated_LTV
4586         8550.0
6118         8510.4
4610         8481.6
3205         8467.2
6768         8460.0

In [9]:
df.to_csv(
    "../../data/processed/ltv_dataset.csv",
    index=False
)

## Observation

- Created Estimated LTV feature.
- Calculated customer lifetime revenue estimate.
- Analyzed LTV statistics.
- Identified high-value customers.
- Saved updated dataset for future analysis.