In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("../../data/processed/day10_feature_engineering.csv")

In [3]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,Avg_Monthly_Spend
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No,14.925000
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,No,No,No,One year,No,Mailed check,56.95,1889.50,No,53.985714
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,36.050000
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No,40.016304
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,50.550000

In [4]:
df['Tenure_Group'] = pd.cut(
    df['tenure'],
    bins=[0, 12, 24, 48, 72],
    labels=['New', 'Regular', 'Loyal', 'Very Loyal']
)

In [5]:
df['Tenure_Group'].value_counts()

Tenure_Group
Very Loyal    2239
New           2175
Loyal         1594
Regular       1024
Name: count, dtype: int64

In [6]:
df['Charge_Segment'] = pd.cut(
    df['MonthlyCharges'],
    bins=[0, 35, 70, 120],
    labels=['Low', 'Medium', 'High']
)

In [7]:
df['Charge_Segment'].value_counts()

Charge_Segment
High      3583
Low       1735
Medium    1725
Name: count, dtype: int64

In [8]:
df[['tenure',
    'Tenure_Group',
    'MonthlyCharges',
    'Charge_Segment']].head(10)

   tenure Tenure_Group  MonthlyCharges Charge_Segment
0       1          New           29.85            Low
1      34        Loyal           56.95         Medium
2       2          New           53.85         Medium
3      45        Loyal           42.30         Medium
4       2          New           70.70           High
5       8          New           99.65           High
6      22      Regular           89.10           High
7      10          New           29.75            Low
8      28        Loyal          104.80           High
9      62   Very Loyal           56.15         Medium

In [9]:
df.to_csv(
    "../../data/processed/day11_customer_segmentation.csv",
    index=False
)