In [1]:
import pandas as pd

In [7]:
df = pd.read_csv("../../data/processed/feature_engineered_telco.csv")

In [8]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,Avg_Monthly_Spend,Tenure_Group,Charge_Segment,Contract_Risk,Revenue_Per_Tenure
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,Yes,Electronic check,29.85,29.85,No,14.925000,New,Low,3,14.925000
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,No,Mailed check,56.95,1889.50,No,53.985714,Loyal,Medium,2,53.985714
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,Yes,Mailed check,53.85,108.15,Yes,36.050000,New,Medium,3,36.050000
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,No,Bank transfer (automatic),42.30,1840.75,No,40.016304,Loyal,Medium,2,40.016304
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,Yes,Electronic check,70.70,151.65,Yes,50.550000,New,High,3,50.550000

In [9]:
df.shape

(7043, 26)

In [10]:
df.columns

Index(['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn',
       'Avg_Monthly_Spend', 'Tenure_Group', 'Charge_Segment', 'Contract_Risk',
       'Revenue_Per_Tenure'],
      dtype='str')

In [12]:
df.describe()

,SeniorCitizen,tenure,MonthlyCharges,TotalCharges,Avg_Monthly_Spend,Contract_Risk,Revenue_Per_Tenure
count,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000
mean,0.162147,32.371149,64.761692,2281.916928,61.173413,2.309527,61.173413
std,0.368612,24.559481,30.090047,2265.270398,61.019723,0.833755,61.019723
min,0.000000,0.000000,18.250000,18.800000,9.183333,1.000000,9.183333
25%,0.000000,9.000000,35.500000,402.225000,26.274411,2.000000,26.274411
50%,0.000000,29.000000,70.350000,1397.475000,61.150000,3.000000,61.150000
75%,0.000000,55.000000,89.850000,3786.600000,84.940047,3.000000,84.940047
max,1.000000,72.000000,118.750000,8684.800000,1397.475000,3.000000,1397.475000

# Day 24 – Dashboard Tool Setup

### Tasks Completed
- Loaded customer dataset
- Verified dataset structure
- Checked dataset dimensions
- Reviewed column names
- Generated summary statistics

### Result
Dataset successfully prepared for dashboard creation.